services:
  _defaults:
    autoconfigure: true

  EuF\PortfolioBundle\Migration\Version410\ImgSizeMigration:
    arguments:
      - '@database_connection'

  EuF\PortfolioBundle\Migration\Version500\BooleanFieldsMigration:
    arguments:
      - '@database_connection'
